name: Deploy to Hostinger

on:
  push:
    branches:
      - master # Replace with the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Step 2: Instal pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v4

      # Step 3: Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0 # Match your SvelteKit project's Node.js version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: pnpm install

      # Step 4: Build the project
      - name: Build the project
        run: pnpm run build

      #  Step 5: Deploy to Hostinger via SFTP
      - name: Deployment to Hostinger
        uses: anvil-solutions/Fast-FTP-Action@2.1.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          port: ${{ secrets.FTP_PORT }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}

          
